import Link from "next/link";
import Home from "./page";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <>
          <Link href="/Get">Get</Link>
          <Link href="/set">Set</Link>
        </>
        <div>{children}</div>
      </body>
    </html>
  );
}
