"use client";

import Header from "./components/Header";
import { WagmiConfig, createConfig, configureChains, useAccount } from "wagmi";
import { hardhat } from "wagmi/chains";
import { publicProvider } from "wagmi/providers/public";
import { MetaMaskConnector } from "wagmi/connectors/metaMask";
import { EthProvider } from "./contexts/eth_context";
import NotConnected from "./components/NotConnected";

const { chains, publicClient, webSocketPublicClient } = configureChains(
  [hardhat],
  [publicProvider()]
);

const config = createConfig({
  autoConnect: false,
  connectors: [new MetaMaskConnector({ chains })],
  publicClient,
  webSocketPublicClient,
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  const { isConnected, address } = useAccount();

  return (
    <html lang="en">
      <body>
        <WagmiConfig config={config}>
          <EthProvider>
            <Header />

            {isConnected ? (
              <>
                <div>{children}</div>
              </>
            ) : (
              <>
                <NotConnected />
              </>
            )}
          </EthProvider>
        </WagmiConfig>
      </body>
    </html>
  );
}
